name: yoga_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  #easy ui design
  velocity_x: ^3.6.0
  #slidable widget
  flutter_slidable: ^2.0.0
  #local storage using hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #shared preferences
  shared_preferences: ^2.0.17
  #heat map
  flutter_heatmap_calendar: ^1.0.5
  #calendar
  intl: ^0.17.0
  #multiselect form
  multiselect_formfield: ^0.1.7
  #firebase core
  firebase_core: ^2.6.1
  #firebase authentication
  firebase_auth: ^4.2.8
  #google sign in
  google_sign_in: ^5.4.4
  #progress bar
  percent_indicator: ^3.0.1
  #image for music
  cached_network_image: ^3.2.3
  # audio bar
  audio_video_progress_bar: ^1.0.0
  #audio package
  just_audio: ^0.9.31
  #background audio
  just_audio_background: ^0.0.1-beta.9
  #combine streams
  rxdart: ^0.27.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_switch: ^0.3.2
  #hive
  hive_generator: ^1.1.3
  build_runner: ^2.1.11


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/files/
    - assets/google_fonts/
    - assets/audio/

